In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [3]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x = np.zeros((10, 10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
x = np.linspace(1., 20., 8)
x

array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
       14.57142857, 17.28571429, 20.        ])

In [6]:
x = np.arange(1, 10, 6)
x

array([1, 7])

In [7]:
import numpy as np

In [8]:
data = np.random.randn(2, 3)

In [9]:
data

array([[ 0.08657893, -0.08446751,  1.43111742],
       [-1.09378583,  0.06544535,  1.12935467]])

In [10]:
data * 10

array([[  0.86578925,  -0.8446751 ,  14.31117422],
       [-10.93785831,   0.65445349,  11.29354667]])

In [11]:
data + data

array([[ 0.17315785, -0.16893502,  2.86223484],
       [-2.18757166,  0.1308907 ,  2.25870933]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [14]:
data1 = [1, 2, 3, 4, 5, 6]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([1, 2, 3, 4, 5, 6])

In [17]:
data2 = (1, 2, 3, 4)
arr2 = np.array(data2)
arr2

array([1, 2, 3, 4])

In [18]:
data2 = [[1, 2, 3, 4], [5, 6, 7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr2.dtype

dtype('int32')

In [22]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.asarray?

In [26]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [27]:
arr > arr

array([[False, False, False, False],
       [False, False, False, False]])

In [28]:
arr == arr

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
arr = np.arange(10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[5]

5

In [32]:
arr[2:4]

array([2, 3])

In [33]:
arr[5:8] = 12

In [34]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr_slice = arr[5:8]

In [36]:
arr_slice

array([12, 12, 12])

In [37]:
arr_slice[1] = 12345

In [38]:
arr_slice

array([   12, 12345,    12])

In [39]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [40]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr2d.ndim

2

In [43]:
arr2d.shape

(3, 3)

In [44]:
arr2d[1]

array([4, 5, 6])

In [45]:
arr2d[1][2]

6

In [46]:
arr2d[2, 0]

7

In [47]:
arr3d = np.array([[[1,2,3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d.ndim

3

In [49]:
arr3d.shape

(2, 2, 3)

In [50]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr3d[0, 1]

array([4, 5, 6])

In [52]:
old_values = arr3d[0].copy()

In [53]:
arr3d[0] = 42

In [54]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [55]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr3d[0] = old_values

In [57]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
#indexing with slices
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [61]:
arr2d[1, :2]

array([4, 5])

In [62]:
arr3d[:1, :1, :2]

array([[[1, 2]]])

In [63]:
arr2d[1:, 0:2] = 0

In [64]:
arr2d

array([[1, 2, 3],
       [0, 0, 6],
       [0, 0, 9]])

In [65]:
arr2d[2, 2]

9

In [66]:
arr2d[2, 2] = 0

In [67]:
arr2d

array([[1, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [68]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[1, :, 1:] = 0

In [70]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  0,  0],
        [10,  0,  0]]])

In [71]:
names = np.array(['Bob', 'Bob', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [72]:
data = np.random.randn(7, 4)

In [73]:
names

array(['Bob', 'Bob', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [74]:
data

array([[-0.69538567,  0.01324085, -2.17332923,  0.72292426],
       [ 0.82744728,  1.35947752,  2.60408357, -0.32693864],
       [ 0.50364004,  0.21578465, -0.40757429,  0.68321076],
       [-0.85949772, -0.91869283,  0.96508893,  1.91250453],
       [ 0.44430101,  0.49406608, -0.29333642, -0.49894856],
       [-0.38707845,  0.27896319, -1.15072689,  0.07501721],
       [ 0.02257307,  0.65782844, -1.71088687,  2.81710963]])

In [75]:
names == 'Bob'

array([ True,  True, False,  True, False, False, False])

In [76]:
data[names == 'Bob']

array([[-0.69538567,  0.01324085, -2.17332923,  0.72292426],
       [ 0.82744728,  1.35947752,  2.60408357, -0.32693864],
       [-0.85949772, -0.91869283,  0.96508893,  1.91250453]])

In [77]:
data [data < 0] = 0

In [78]:
data

array([[0.        , 0.01324085, 0.        , 0.72292426],
       [0.82744728, 1.35947752, 2.60408357, 0.        ],
       [0.50364004, 0.21578465, 0.        , 0.68321076],
       [0.        , 0.        , 0.96508893, 1.91250453],
       [0.44430101, 0.49406608, 0.        , 0.        ],
       [0.        , 0.27896319, 0.        , 0.07501721],
       [0.02257307, 0.65782844, 0.        , 2.81710963]])

In [79]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [80]:
z = np.zeros((10, 10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [81]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [82]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [83]:
arr = arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [84]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [85]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [86]:
i = np.ones((3,3))
print(i)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [87]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.68353652 0.3455506  0.96026413]
  [0.61817279 0.25019879 0.99286933]
  [0.91552365 0.15143085 0.03231318]]

 [[0.07158693 0.81718229 0.85551153]
  [0.59135334 0.79128262 0.83476539]
  [0.24034456 0.82882218 0.17691572]]

 [[0.69813155 0.07155093 0.26486925]
  [0.24229017 0.9879821  0.56115788]
  [0.77553353 0.6089458  0.9042181 ]]]


In [88]:
arr = np.random.random((10,10))
arr_min = arr.min()
arr_max = arr.max()
print(arr_min)
print(arr_max)

0.007185123844609231
0.9981196483564502


In [89]:
arr = np.random.random(30)
arr_mean = arr.mean()
print(arr)
print(arr_mean)

[0.48603861 0.37123045 0.77768377 0.44550697 0.27872982 0.03332315
 0.67216335 0.85349939 0.6143695  0.79382182 0.75872377 0.95450585
 0.36923696 0.77656112 0.96070924 0.06386026 0.70773164 0.32035171
 0.84830615 0.95743196 0.01405539 0.59548929 0.56818723 0.80522401
 0.00964982 0.62327237 0.66681879 0.028003   0.04614583 0.16670376]
0.518911166890054


In [90]:
arr = np.ones((5,5))
print(arr)
arr[:,[0,-1]] = 0
arr[[0, -1], :] = 0
print("===========after swaping border with 0")
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
===========after swaping border with 0
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [95]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set in set ([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan


TypeError: argument of type 'type' is not iterable

In [96]:
z = np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
