In [1]:
import numpy as np

# creating array of different dimensions

In [37]:
arr = np.array(42)

print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [38]:
arr1 = np.array([1,2,3,4])

print(arr1)

[1 2 3 4]


In [39]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [40]:

arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(arr3)
print(type(arr3))

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>


In [41]:
#checking dimesnions of array


print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [42]:
#creating arrays of higher of dimensions

arr5 = np.array([1,2,3,4,5], ndmin=5)

print(arr5)

print("Number of dimensions: ", arr5.ndim)

# accessing elements
print(arr5[0,0,0,0,4])

[[[[[1 2 3 4 5]]]]]
Number of dimensions:  5
5


In [26]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

print("2nd dim on 1st element:" ,arr2[0,1])

2nd dim on 1st element: 2


# Array indexing

In [32]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,8,9]]])

print("3rd dim:", arr3[0,1,2])

3rd dim: 7
