In [1]:
Ist =[[1,2,3]
     ,[4,5,6],[98,21,32]]
for i in range(0,3):
    print(Ist[i].pop(), end="")

3632

In [2]:
print(2)
print(3)
print(4)

2
3
4


In [3]:
print(2 , end="")
print(3)
print(4)

23
4


In [4]:
print(2 , end="")
print(3 , end="")
print(4)

234


In [5]:
29.0 ==29

True

In [6]:
29.0 =="29"

False

In [8]:
dic = {}
Ist = ["x" , "y" , "z" , "a"]
for i in range(len(Ist)-1):
    dic[Ist[i]] = (Ist[i],)
for i in sorted(dic.keys()):
    k =dic[i]
    print(k[0])
print(dic)

x
y
z
{'x': ('x',), 'y': ('y',), 'z': ('z',)}


In [9]:
tup = (1,2,3)
tup.append(4)
print(tup[-1])

AttributeError: 'tuple' object has no attribute 'append'

In [13]:
0.1 + 0.2 == 0.3 # note the logic

False

In [12]:
0.1+0.2

0.30000000000000004

In [15]:
0.1 + 0.1 == 0.2

True

In [17]:
0.1 + 0.5 == 0.6

True

In [18]:
my_name = "Waqas Ali"
print(my_name[3:5]) # note the logic

as


In [23]:
l = [1,3,5,7,9,11]
l = [1,3,5,7,9,11]
for i in range(1,6):
    l[i-1] = l[i]
for i in range(0,6):
    print(l[i] , end="")

35791111

In [25]:
if "course" in {"name": "sanwal" , "course":"AI"}:
    print("OK")
    print("Yes")
if "c" in "sea":
    print("ocean")
print("over")

OK
Yes
over


In [27]:
maths = 2/4 + 4//4 + 4**2
print(maths)

17.5


In [30]:
print(1,2,2020, sep=" ") # note the logic

1 2 2020


In [31]:
print(1,2,2020, sep="/") # note the logic

1/2/2020


In [32]:
print(1,2,2020, sep=",") # note the logic

1,2,2020


In [34]:
print(1,2,2020)

1 2 2020


In [35]:
students = {"ali": 1 , 2: "student"}
2 in students

True

In [37]:
a = 9%3
b = (5*a+5)//2
print(b)

2


In [41]:
6/3  # note

2.0

In [42]:
6//3 #note 

2

In [44]:
l = [2 , 3]
for k in range(2):
    l.insert(-1,l[k])
print(l)

[2, 2, 2, 3]


In [45]:
range(2)

range(0, 2)

In [46]:
a = 3
b = str(3)
print(a*b +b)

3333


In [47]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [48]:
"A.I"*3

'A.IA.IA.I'

In [49]:
t = (1,2,3,4)
t =t[2-2]
t =t[0]
print(t)

TypeError: 'int' object is not subscriptable

In [51]:
t = (1,2,3,4)
t =t[2-2]

print(t)

1


In [53]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

In [54]:
if a<b:ifa>9:print("ok")

SyntaxError: illegal target for annotation (<ipython-input-54-ec431be6ca7e>, line 1)

In [55]:
if False:
    print("Ok")

In [56]:
fruits = ["Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes","Apple" , "Mango" , "grapes",]

In [57]:
print(fruits)

['Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes', 'Apple', 'Mango', 'grapes']


In [69]:
count = 0
for i in fruits:
    if i == "Apple":
        count = count+1
    
print(f'Apple: {count}')

Apple: 21


In [70]:
len(fruits)

63

In [75]:
print(fruits.count("Apple"))
print(fruits.count("Mango"))

21
21


In [76]:
import os

In [77]:
os.getcwd()

'D:\\Sanwal\\python'

In [78]:
os.listdir()

[' 2 variabe and data type.ipynb',
 '.ipynb_checkpoints',
 '1 programming file.ipynb',
 '3 Lists  and for loop.ipynb',
 'abc.txt',
 'ai.csv',
 'Assignment#1.ipynb',
 'assignment2.ipynb',
 'Classes (OOP).ipynb',
 'data.txt',
 'Dictionary.ipynb',
 'files and exception.ipynb',
 'Functions.ipynb',
 'list.json',
 'Load module and Working with Files.ipynb',
 'Nested loops , Tuple and Input.ipynb',
 'paractis.ipynb',
 'Practice1.ipynb',
 'revision.ipynb',
 'test practice.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'xyz.txt']

In [80]:
len(os.listdir('D:\\Sanwal\\python'
))

28

In [81]:
os.mkdir("new folder")

In [82]:
os.mkdir("new folder")

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'new folder'

In [83]:
os.path.exists("new folder")

True

In [84]:
os.system("chrome")

1

In [87]:
os.system("calculator")

1

In [88]:
time
datetime

NameError: name 'time' is not defined

In [89]:
import time

In [90]:
time.time() # current time in sec

1583649127.9763484

In [91]:
time.time()

1583649150.562789

In [92]:
time.time()

1583649158.8829546

In [94]:
startTime = time.time()

a = input("Enter something")

endTime= time.time()
endTime - startTime

Enter somethingsanwal


5.0065507888793945

In [95]:
startTime = time.time()

a = input("Enter something")
time.sleep(20)

endTime= time.time()
endTime - startTime

Enter somethingajbf,ajs


23.41181230545044

In [96]:
import math

In [97]:
math.factorial(5)

120

In [99]:
math.cos(1)

0.5403023058681398

In [100]:
math.sin(90)

0.8939966636005579

In [102]:
startTime = time.time()
math.factorial(5)
time.time() - startTime

0.0

In [103]:
startTime = time.time()
math.factorial(1000)
time.time() - startTime

0.0

In [107]:
math.cos(90)

-0.4480736161291701

In [108]:
import datetime

In [112]:
datetime.datetime.now()

datetime.datetime(2020, 3, 8, 11, 46, 58, 854345)

<attribute 'year' of 'datetime.date' objects>

In [3]:
import numpy as np
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])
print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [4]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [5]:
a

array([0, 1, 2, 3, 4])

In [8]:
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


In [12]:
a = np.arange(5)
a.()

2.0

In [ ]:
np.mean()

In [21]:
import numpy as np

list1 = [0,1,2,3,4,5,6,7,8] 
def calculate(list1):
    list1 = np.reshape(list1, (3,3))
    calculations={
      'mean': np.mean(list1),
      'variance': np.var(list1),
      'standard deviation':np.std(list1),
      'max':np.max(list1),
      'min':np.min(list1),
      'sum':np.sum(list1)
      }
    return calculations

calculate(list1)

{'mean': 4.0,
 'variance': 6.666666666666667,
 'standard deviation': 2.581988897471611,
 'max': 8,
 'min': 0,
 'sum': 36}

In [23]:
import pandas as pd
list = ['A', 'B', 'A', 'A']
list_count = pd.Series(list).count()
list_count

4

In [24]:
s = pd.Series(np.arange(5))
s.mean()

2.0

In [28]:
df = pd.DataFrame({'X':['M','B','B','M','B'], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})
df

X   Y   Z
0  M  84  86
1  B  94  97
2  B  89  96
3  M  83  72
4  B  86  83

In [76]:
df_X = df.iloc[:]['X']
print(df_X)
df_Xcount = df_X.count()
df_Xcount

0    M
1    B
2    B
3    M
4    B
Name: X, dtype: object


5

In [73]:
df_Bcounts = df_X[df_X[:] == 'B'].count()
df_Bcounts

3

In [75]:
df_Bpercent = df_Bcounts/ len(df_X) * 100
df_Bpercent

60.0

In [78]:
dic={
    'men':['A', 'B', 'C'],
    'hours_per_week': [30, 30, 40],
    'salary':[50000, 50000, 10000]
}

df=pd.DataFrame(dic)
df

men  hours_per_week  salary
0   A              30   50000
1   B              30   50000
2   C              40   10000

In [86]:
mini_hours_week = df['hours_per_week'].min()
df[df.iloc[1]== mini_hours_week]

<ipython-input-86-3a796ae05065>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.iloc[1]== mini_hours_week]


IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [87]:
import numpy as np

a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()

In [88]:
b

15

In [89]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [90]:
np.max(a, axis=1)

array([ 5, 10])

In [1]:
import pandas as pd

In [4]:
samosa_sale = pd.Series([150,200,160,150,0,0,0], ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday','sunday'])
print(samosa_sale)

monday       150
tuesday      200
wednesday    160
thursday     150
friday         0
saturday       0
sunday         0
dtype: int64
